### ISSUE TITLE
Why are there some problems with the displayed images when using the ieee style?

### ISSUE THREAD

**Issue by kongxinz** [garrettj403/SciencePlots#60] opened 2022-05-22 02:25 UTC

**Comment by kongxinz** [comment] 2022-05-22 02:26
![Uploading QQ截图20220522102513.png…]()

**Comment by kongxinz** [comment] 2022-05-22 02:26
![Uploading fig.1.png…]()

**Comment by echedey-ls** [comment] 2022-05-22 08:42
Please, check how you have shared the image.
Follow [this StackOverflow answer](https://stackoverflow.com/a/32933632) so we can see the image:.

**Comment by kongxinz** [comment] 2022-05-22 08:44
I'm sorry, but the problem was caused by the fact that I didn't set the correct resolution when exporting the image. The issue is now resolved, thanks a lot.

**Comment by echedey-ls** [comment] 2022-05-22 09:12
Still can't see it. Can you check without login in GitHub?

**Comment by kongxinz** [comment] 2022-05-22 09:16
![fig 1](https://user-images.githubusercontent.com/74749542/169688231-66a3bf49-2da8-4147-abba-0719d418a341.png)

**Comment by echedey-ls** [comment] 2022-05-22 09:26
Can you also provide the code?

**Comment by echedey-ls** [comment] 2022-05-23 19:42
I've done some minimal testing and found a workaround for that.
Go to your `ieee.myplstyle` ([should look like this file](https://github.com/garrettj403/SciencePlots/blob/master/styles/journals/ieee.mplstyle), mine was, in Windows, in user/.matplotlib/stylelib) and comment line 10 with a `#`. I believe it will mess up with the standard but at least you now know what to change to have better results.

**Comment by echedey-ls** [comment] 2022-06-14 05:24
I recommend against closing this issue.
Although I've provided a workaround, it's still an issue and many people will come here looking for advice or to report the same.

I don't really know much about DPI and how it works on each level, but from [this stackoverflow post](https://stackoverflow.com/questions/47633546/relationship-between-dpi-and-figure-size) I think the problem is with the huge DPI on this style.

**Comment by kongxinz** [comment] 2022-06-14 05:24
This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank you！

**Comment by garrettj403** [comment] 2022-06-15 19:22
I added a note to the IEEE style in the project wiki ([link](https://github.com/garrettj403/SciencePlots/wiki/Gallery#styles-for-specific-academic-journals)).

**Closed by garrettj403** 2022-06-15 19:22 UTC

**Comment by echedey-ls** [comment] 2022-06-15 19:47
I should let you know that when I put the 125 dpi I didn't bother to find the default value for it. It is in fact 100, so for the wiki it would be better to specify it. Sorry for not changing it before.
Also, thanks for the nice work put into this.

**Comment by kongxinz** [comment] 2022-10-11 07:17
This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank you！
